/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Classes.Add;
import Classes.loginSession;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author aiden
 */
public class AddNewWorker extends javax.swing.JFrame {
    loginSession ls;
    
    /**
     * Creates new form AddNewWorker
     */
    private TableRefreshListener refreshListener;
    
    public AddNewWorker(TableRefreshListener refreshListener, loginSession session) {
        initComponents();
        this.hidePassword.setVisible(false);
        this.hidePassword1.setVisible(false);
        this.ls = session;
        String userId = ls.getId();
        this.refreshListener = refreshListener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        contactNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        showPassword = new javax.swing.JLabel();
        hidePassword = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cfmPassword = new javax.swing.JPasswordField();
        showPassword1 = new javax.swing.JLabel();
        hidePassword1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 310, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Add New Worker");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 240, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Confirm Password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 256, -1, -1));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 240, 30));

        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setText("* Password atleast 1 Upper, 1 Lower, 1 Digit, ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 240, 20));

        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("1 Special Character and atleast 8 Characters");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 240, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Role:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Contact:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        contactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNoActionPerformed(evt);
            }
        });
        contactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactNoKeyTyped(evt);
            }
        });
        getContentPane().add(contactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 240, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Email:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 240, 30));

        showPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/showPassword.png"))); // NOI18N
        showPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showPasswordMousePressed(evt);
            }
        });
        getContentPane().add(showPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, -1));

        hidePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hidePassword.png"))); // NOI18N
        hidePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hidePasswordMousePressed(evt);
            }
        });
        getContentPane().add(hidePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, -1));

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "officer", "salesperson" }));
        getContentPane().add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 240, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Password:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));
        getContentPane().add(cfmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 256, 240, 30));

        showPassword1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/showPassword.png"))); // NOI18N
        showPassword1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showPassword1MousePressed(evt);
            }
        });
        getContentPane().add(showPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 248, -1, -1));

        hidePassword1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hidePassword.png"))); // NOI18N
        hidePassword1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hidePassword1MousePressed(evt);
            }
        });
        getContentPane().add(hidePassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 248, -1, -1));

        btnExit.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        btnExit.setText("Back");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 130, -1));

        btnReset.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 130, -1));

        btnAdd.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 130, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void contactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNoActionPerformed

    private void contactNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNoKeyTyped
        //for disable character input
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_contactNoKeyTyped

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void showPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPasswordMousePressed
        hidePassword.setVisible(true);
        showPassword.setVisible(false);
        password.setEchoChar((char)0);
    }//GEN-LAST:event_showPasswordMousePressed

    private void hidePasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePasswordMousePressed
        hidePassword.setVisible(false);
        showPassword.setVisible(true);
        password.setEchoChar('*');
    }//GEN-LAST:event_hidePasswordMousePressed

    private void showPassword1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPassword1MousePressed
        hidePassword1.setVisible(true);
        showPassword1.setVisible(false);
        cfmPassword.setEchoChar((char)0);
    }//GEN-LAST:event_showPassword1MousePressed

    private void hidePassword1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePassword1MousePressed
        hidePassword1.setVisible(false);
        showPassword1.setVisible(true);
        cfmPassword.setEchoChar('*');
    }//GEN-LAST:event_hidePassword1MousePressed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int n = JOptionPane.showConfirmDialog(null, "Are you sure you don't want to add new worker?", "Go Back", JOptionPane.YES_NO_OPTION);
        if (n==JOptionPane.YES_OPTION){
            ManageWorkerProfile a =new ManageWorkerProfile(ls);
            a.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        name.setText("");
        password.setText("");
        cfmPassword.setText("");
        role.setSelectedItem("");
        contactNo.setText("");
        email.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String n,p,cp,r,c,e;

        n=name.getText();
        if(n.trim().equals("")) {
            JOptionPane.showMessageDialog(null,"Please fill in your name!","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!n.matches("[a-zA-Z\\s]+")) {
            JOptionPane.showMessageDialog(null,"Name should contain only letters and spaces","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        p=String.valueOf(password.getPassword());
        // Check if the password meets the specified criteria
        if (!p.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*()_+={}|;:',.?/`~<>]).{8,}$")) {

            JOptionPane.showMessageDialog(null,
                    "Password must have at least 8 characters with at least one uppercase letter, one lowercase letter, one digit, and one special character",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        cp=String.valueOf(cfmPassword.getPassword());
        if (!cp.equals(p)) {
            JOptionPane.showMessageDialog(null, "Confirm Password must be same as Password",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        r=String.valueOf(role.getSelectedItem());
        
        c=contactNo.getText();
        if(c.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill in Contact Number!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(c.trim().length() < 7 || c.trim().length() > 15){
            JOptionPane.showMessageDialog(null, "Invalid Contact Number! (min 7 max 15)", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        e=email.getText();
        if(e.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill in Email Address!", "Error", JOptionPane.ERROR_MESSAGE);
            return ;
        }
        String emailPattern = "^(.+)@(\\S+)$";
        if(!e.matches(emailPattern)) {
            JOptionPane.showMessageDialog(null, "Please enter a valid Email", "Error", JOptionPane.ERROR_MESSAGE);
            return ;
        }

        Add obj1 = new Add(n,p,cp,r,c,e);
        String res=obj1.addNewWorker();
        if(res== "Success"){
            JOptionPane.showMessageDialog(null,"Successfully Add new Worker.","Success",JOptionPane.INFORMATION_MESSAGE);
            ManageWorkerProfile a =new ManageWorkerProfile(ls);
            a.setVisible(true);
            this.setVisible(false);
            onClose();
        }else{
            JOptionPane.showMessageDialog(null, "Could not write into file due to "+res,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    // This method is called when the window is closed
    private void onClose() {
        if (refreshListener != null) {
            refreshListener.onTableRefresh();
        }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddNewWorker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddNewWorker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddNewWorker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddNewWorker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddNewWorker().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JPasswordField cfmPassword;
    private javax.swing.JTextField contactNo;
    private javax.swing.JTextField email;
    private javax.swing.JLabel hidePassword;
    private javax.swing.JLabel hidePassword1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JLabel showPassword;
    private javax.swing.JLabel showPassword1;
    // End of variables declaration//GEN-END:variables
}
