/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Classes.loginSession;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author aiden
 */
public class ManageWorkerProfile extends javax.swing.JFrame implements TableRefreshListener{
    loginSession ls;
    
    /**
     * Creates new form ManageWorkerProfile
     */
    public ManageWorkerProfile(loginSession session) {
        initComponents();
        this.ls = session;
        String userId = ls.getId();
        populateTable();
    }
    
    public void populateTable() {
    String[] columns = {"ID", "Name", "Password", "Role", "Contact Number", "Email", "Status"};
    DefaultTableModel model = new DefaultTableModel(columns, 0){
    @Override
    public boolean isCellEditable(int row, int column){
        return false;
    }
};
    
    //bufferReader reads data faster and efficient only
    try (BufferedReader br = new BufferedReader(new FileReader("user.txt"))) { //read file
        String line;
        while ((line = br.readLine()) != null) { //if file is not empty
            String[] data = line.split(", "); 
            // Check if the role is not "admin" before adding data to the table
            if (!data[3].equals("admin")) {
                model.addRow(data); //add data to table
            }
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
    
    jTable1.setModel(model);
    jTable1.setRowSelectionAllowed(true);
    jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnViewProfile = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnAddWorker = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1020, 615));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.setMaximumSize(new java.awt.Dimension(1000, 600));
        btnBack.setMinimumSize(new java.awt.Dimension(1000, 600));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 16, 100, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Password", "Role", "Contact Number", "Email", "Status"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 988, 388));

        btnViewProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnViewProfile.setText("View Profile");
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 180, 45));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Manage Worker");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Search by Staff ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 40, 126, -1));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 62, 270, 28));

        btnAddWorker.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddWorker.setText("Add New Worker");
        btnAddWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWorkerActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddWorker, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 180, 45));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdminMainMenu a =new AdminMainMenu(ls);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow>=0){ //if table has data
            String[] rowData = new String[jTable1.getModel().getColumnCount()];
            for (int i = 0; i < jTable1.getModel().getColumnCount(); i++) {
                rowData[i] = (String) jTable1.getModel().getValueAt(selectedRow, i); //fetch all the selected data in that row
            }
            
            // create a new window to display the selected row data
            // pass "this" frame (ManageWorkerProfile) as a listener to WorkerProfilePage
            WorkerProfilePage a = new WorkerProfilePage(rowData, this, ls);
            a.setVisible(true);
            a.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }else{
            JOptionPane.showMessageDialog(null, "Please select a staff");
        }
    }//GEN-LAST:event_btnViewProfileActionPerformed

    @Override
    public void onTableRefresh() {
        populateTable();
    }
    
    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String search = txtSearch.getText();
        DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
        TableRowSorter<DefaultTableModel> tData = new TableRowSorter<>(table);
        jTable1.setRowSorter(tData);
        tData.setRowFilter(new RowFilter<DefaultTableModel, Object>() {
        @Override
        public boolean include(Entry<? extends DefaultTableModel, ? extends Object> entry) {
            // Add your custom conditions here
            // For example, filter based on ID (assuming ID is in the first column)
            String id = entry.getStringValue(0);
            return id.startsWith(search);
        }
    });
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnAddWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWorkerActionPerformed
        AddNewWorker a =new AddNewWorker(this, ls);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddWorkerActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ManageWorkerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ManageWorkerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ManageWorkerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ManageWorkerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ManageWorkerProfile().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddWorker;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
