/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package officer_role;

import Classes.loginSession;
import Classes.Officer;
import com.mycompany.YoYoFurniture.login;
import java.util.ArrayList;

/**
 *
 * @author mahpi
 */
public class OfficerMainMenu extends javax.swing.JFrame {
    loginSession ls;
    /**
     * Creates new form OfficerMainMenu
     * @param session
     */
    
    public OfficerMainMenu(loginSession session) {
        initComponents();
        this.ls = session;
        String id = ls.getId();
        
        Officer officer = new Officer();
        ArrayList<String[]> userDataList = officer.importUsers(id);
        for(String[] data:userDataList){
            String officerId = data[0];
            String username =  data[1];
            if(id.equals(officerId)){
                usernameTxt.setText(username);
            }
        }   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JLabel();
        btnManagePersonalProfile = new javax.swing.JButton();
        btnViewSalesOrder = new javax.swing.JButton();
        btnGenerateReport = new javax.swing.JButton();
        btnGenerateInvoice = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(78, 196, 157));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Officer Portal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 589, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 880, 70));

        jPanel1.setBackground(new java.awt.Color(78, 196, 157));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Officer Portal");

        usernameTxt.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        usernameTxt.setForeground(new java.awt.Color(255, 255, 255));
        usernameTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameTxt.setText("Username");
        usernameTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTxt)
                .addGap(156, 156, 156))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 250, 400));

        btnManagePersonalProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manage-personal-profile.png"))); // NOI18N
        btnManagePersonalProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(78, 196, 157), 3));
        btnManagePersonalProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManagePersonalProfile.setMaximumSize(new java.awt.Dimension(204, 204));
        btnManagePersonalProfile.setMinimumSize(new java.awt.Dimension(204, 204));
        btnManagePersonalProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePersonalProfileActionPerformed(evt);
            }
        });
        getContentPane().add(btnManagePersonalProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 230, 170));

        btnViewSalesOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view-sales-order.png"))); // NOI18N
        btnViewSalesOrder.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(78, 196, 157), 3, true));
        btnViewSalesOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewSalesOrder.setMaximumSize(new java.awt.Dimension(204, 204));
        btnViewSalesOrder.setMinimumSize(new java.awt.Dimension(204, 204));
        btnViewSalesOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSalesOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewSalesOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 230, 170));

        btnGenerateReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generate-report.png"))); // NOI18N
        btnGenerateReport.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(78, 196, 157), 3, true));
        btnGenerateReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerateReport.setMaximumSize(new java.awt.Dimension(204, 204));
        btnGenerateReport.setMinimumSize(new java.awt.Dimension(204, 204));
        btnGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerateReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 230, 170));

        btnGenerateInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/manageSalesOrder.png"))); // NOI18N
        btnGenerateInvoice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(78, 196, 157), 3, true));
        btnGenerateInvoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerateInvoice.setMaximumSize(new java.awt.Dimension(204, 204));
        btnGenerateInvoice.setMinimumSize(new java.awt.Dimension(204, 204));
        btnGenerateInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateInvoiceActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerateInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 230, 170));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/officerProfile.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        login a =new login();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnManagePersonalProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePersonalProfileActionPerformed
        ProfileInterface a =new ProfileInterface(ls);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnManagePersonalProfileActionPerformed

    private void btnViewSalesOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSalesOrderActionPerformed
        SaleOrderGUI a = new SaleOrderGUI(ls);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnViewSalesOrderActionPerformed

    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
        GenerateReport a = new GenerateReport(ls);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    private void btnGenerateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateInvoiceActionPerformed
        ApproveSales a = new ApproveSales(ls);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGenerateInvoiceActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(OfficerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(OfficerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(OfficerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(OfficerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new OfficerMainMenu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateInvoice;
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManagePersonalProfile;
    private javax.swing.JButton btnViewSalesOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel usernameTxt;
    // End of variables declaration//GEN-END:variables
}
