/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package officer_role;

import Classes.Officer;
import Classes.Salesperson;
import Classes.loginSession;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author User
 */

public class ProfileInterface extends javax.swing.JFrame {
    loginSession ls;
    public ProfileInterface(loginSession session) {
        initComponents();
        this.ls = session;
        String userId = ls.getId();
        
        Officer officer = new Officer();
        ArrayList<String[]> userDataList = officer.importUsers(userId);
  
        for (String[] data : userDataList) {
            id.setText(data[0]);
            name.setText(data[1]);   
            contactNo.setText(data[4]);
            email.setText(data[5]);
            status.setText(data[6]);
             //Set background color of status
                if ("active".equalsIgnoreCase(data[6])){
                    status.setBackground(new Color(0, 204, 51));
                }else if ("inactive".equalsIgnoreCase(data[6])) {
                    status.setBackground(new Color(255, 51, 0));
                }
                // Make the background opaque because original is transparent
                status.setOpaque(true);
        }
        this.setLocationRelativeTo(null);//set the location to center
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profileIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        UserDescription = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        UserDescription1 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        contactNo = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-administrator-male-96.png"))); // NOI18N
        getContentPane().add(profileIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, 114));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setText("User Profile");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        UserDescription.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        UserDescription.setText("of Yoyo-Furniture Company");
        getContentPane().add(UserDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel4.setText("Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 64, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel8.setText("Email:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 70, -1));

        UserDescription1.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        UserDescription1.setText("Officer Role");
        getContentPane().add(UserDescription1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        BackButton.setBackground(new java.awt.Color(255, 0, 51));
        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 67, -1));

        EditButton.setBackground(new java.awt.Color(0, 153, 153));
        EditButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EditButton.setForeground(new java.awt.Color(255, 255, 255));
        EditButton.setText("Edit");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 67, -1));

        name.setText("jLabel2");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        email.setText("jLabel3");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel9.setText("Account Status:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 110, -1));

        contactNo.setText("jLabel4");
        getContentPane().add(contactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        id.setBackground(new java.awt.Color(255, 255, 153));
        id.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id.setText("jLabel1");
        id.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.lightGray));
        id.setOpaque(true);
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 120, 30));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel10.setText("Contact Number:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 110, -1));

        status.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status.setText("jLabel6");
        status.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.gray));
        status.setOpaque(true);
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 80, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 300, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 300, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 300, 10));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 300, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        OfficerMainMenu a = new OfficerMainMenu(ls);
        a.setVisible(true); 
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        officer_role.ManagePersonalProfile a =new officer_role.ManagePersonalProfile(ls);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EditButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ProfileInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ProfileInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ProfileInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ProfileInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ProfileInterface().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JLabel UserDescription;
    private javax.swing.JLabel UserDescription1;
    private javax.swing.JLabel contactNo;
    private javax.swing.JLabel email;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel name;
    private javax.swing.JLabel profileIcon;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
