/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package officer_role;

import Classes.displaySalesInvoice;
import Classes.GeneratePDF;
import Classes.loginSession;
import java.awt.Color;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author User
 */
public class SalesInvoice extends javax.swing.JFrame {
    loginSession ls;
    public SalesInvoice(String customerName, String salesDate, String salesPersonID, String salesID, loginSession session) {
        initComponents();
        this.ls = session;
        
        this.setLocationRelativeTo(null);//set the location to center
        Color background = new Color(242, 241, 235);
        getContentPane().setBackground(background);
        displaySalesInvoice a = new displaySalesInvoice(cusName, cusContact, cusAddress, SalesPersonID, Date, Time, InvoiceTable, subTotal, deliveryFee, serviceTax, total, invoiceID);
        a.display(customerName, salesDate, salesPersonID, salesID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackBtn = new javax.swing.JButton();
        printBtn = new javax.swing.JButton();
        invoicePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        invoiceIcon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        testing2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InvoiceTable = new javax.swing.JTable();
        testing3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        testing = new javax.swing.JLabel();
        testing1 = new javax.swing.JLabel();
        cusName = new javax.swing.JLabel();
        cusContact = new javax.swing.JLabel();
        cusAddress = new javax.swing.JLabel();
        SalesPersonID = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        subTotal = new javax.swing.JLabel();
        deliveryFee = new javax.swing.JLabel();
        serviceTax = new javax.swing.JLabel();
        invoiceID = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackBtn.setBackground(new java.awt.Color(0, 102, 102));
        BackBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(255, 255, 255));
        BackBtn.setText("Cancel");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 90, 30));

        printBtn.setBackground(new java.awt.Color(0, 153, 153));
        printBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        printBtn.setForeground(new java.awt.Color(255, 255, 255));
        printBtn.setText("Print");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });
        getContentPane().add(printBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 90, 30));

        invoicePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INVOICE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 87, -1, -1));

        invoiceIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-invoice.png"))); // NOI18N
        jPanel1.add(invoiceIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 10, -1, 73));

        jLabel2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Washington.DC");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 108, -1, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Yoyo-Furniture Company");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 28, -1, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jalan 5/125, 57100");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bukit Jalil");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 85, -1, -1));

        invoicePanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 140));

        testing2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        testing2.setText("Ship To:");
        invoicePanel.add(testing2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel8.setText("Total (RM):");
        invoicePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 502, -1, -1));

        InvoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SALES ID", "ITEM", "QTY", "UNIT PRICE", "DISCOUNT", "AMOUNT"
            }
        ));
        jScrollPane1.setViewportView(InvoiceTable);

        invoicePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 550, 70));

        testing3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        testing3.setText("SalesPerson ID:");
        invoicePanel.add(testing3, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel11.setText("Invoice ID #:");
        invoicePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel12.setText("Delivery Fee:");
        invoicePanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 439, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel13.setText("Service Tax (6%):");
        invoicePanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 469, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel9.setText("Invoice Date:");
        invoicePanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        Date.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        Date.setText("jLabel14");
        invoicePanel.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        testing.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        testing.setText("Bill To:");
        invoicePanel.add(testing, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        testing1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        testing1.setText("Contact No:");
        invoicePanel.add(testing1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        cusName.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        cusName.setText("jLabel6");
        invoicePanel.add(cusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 210, -1, -1));

        cusContact.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        cusContact.setText("jLabel6");
        invoicePanel.add(cusContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 240, -1, -1));

        cusAddress.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        cusAddress.setText("jLabel6");
        invoicePanel.add(cusAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 270, -1, -1));

        SalesPersonID.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        SalesPersonID.setText("jLabel6");
        invoicePanel.add(SalesPersonID, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        Time.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        Time.setText("jLabel6");
        invoicePanel.add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel14.setText("SubTotal:");
        invoicePanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        jLabel6.setText(",");
        invoicePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 240, -1, -1));

        total.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        total.setText("jLabel7");
        invoicePanel.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 502, -1, -1));

        subTotal.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        subTotal.setText("jLabel7");
        invoicePanel.add(subTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 410, -1, -1));

        deliveryFee.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        deliveryFee.setText("jLabel7");
        invoicePanel.add(deliveryFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 439, -1, -1));

        serviceTax.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        serviceTax.setText("jLabel7");
        invoicePanel.add(serviceTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 469, -1, -1));

        invoiceID.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        invoiceID.setText("jLabel7");
        invoicePanel.add(invoiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 180, -1, -1));

        getContentPane().add(invoicePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 530));

        SubmitButton.setBackground(new java.awt.Color(0, 102, 102));
        SubmitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 90, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Save PDF");
    fileChooser.setAcceptAllFileFilterUsed(false);
    
    // Set the default directory to the user's home directory or any specific path
    fileChooser.setCurrentDirectory(new java.io.File(System.getProperty("user.home")));
    
    // Filter only PDF files
    FileNameExtensionFilter pdfFilter = new FileNameExtensionFilter("PDF Documents", "pdf");
    fileChooser.addChoosableFileFilter(pdfFilter);
    fileChooser.setFileFilter(pdfFilter);

    while (true) {
        int userSelection = fileChooser.showSaveDialog(null);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            java.io.File fileToSave = fileChooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();
            // Ensure the file has a ".pdf" extension
            if (!filePath.toLowerCase().endsWith(".pdf")) {
                filePath += ".pdf";
            }
           
            GeneratePDF generator = new GeneratePDF();
            try {
                generator.panelToPDF(invoicePanel, filePath); // Use the selected file path for PDF generation
                JOptionPane.showMessageDialog(null, "PDF generated successfully and saved to: " + filePath, "Success", JOptionPane.INFORMATION_MESSAGE);
                System.out.println("PDF generated successfully.");
                break; // Exit the loop after successful operation
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Failed to generate PDF.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // User cancelled the operation
            JOptionPane.showMessageDialog(null, "PDF save operation was cancelled.", "Cancelled", JOptionPane.WARNING_MESSAGE);
            break; // Exit the loop if the operation was cancelled
        }
    }
    }//GEN-LAST:event_printBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        ApproveSales a = new ApproveSales(ls);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        String InvoiceID = invoiceID.getText();
        String customerName = cusName.getText();
        String customerContact = cusContact.getText();
        String customerAddress = cusAddress.getText();
        String salesPersonID = SalesPersonID.getText();
        String salesDate = Date.getText();
        String salesTotal = total.getText();

        DefaultTableModel tableModel = (DefaultTableModel) InvoiceTable.getModel();
        List<String> salesIDs = new ArrayList<>();
        List<String> items = new ArrayList<>();
        List<String> quantities = new ArrayList<>();

        for (int row = 0; row < tableModel.getRowCount(); row++) {
            salesIDs.add(tableModel.getValueAt(row, 0).toString());
            items.add(tableModel.getValueAt(row, 1).toString());
            quantities.add(tableModel.getValueAt(row, 2).toString());
        }

        boolean update = displaySalesInvoice.writeSalesInvoice(InvoiceID, customerName, customerContact, customerAddress, salesPersonID, salesDate, salesTotal, salesIDs, items, quantities);
        ApproveSales a = new ApproveSales(ls);
        a.setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_SubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SalesInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SalesInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SalesInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SalesInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                String defaultCustomerName = "Default Customer";
//                String defaultSalesDate = "Default Date";
//                String defaultSalesPersonID = "Default Sales Person ID";
//                String defaultSalesID = "Default Sales ID";
//                new SalesInvoice(defaultCustomerName, defaultSalesDate, defaultSalesPersonID, defaultSalesID).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel Date;
    private javax.swing.JTable InvoiceTable;
    private javax.swing.JLabel SalesPersonID;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel cusAddress;
    private javax.swing.JLabel cusContact;
    private javax.swing.JLabel cusName;
    private javax.swing.JLabel deliveryFee;
    private javax.swing.JLabel invoiceID;
    private javax.swing.JLabel invoiceIcon;
    private javax.swing.JPanel invoicePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printBtn;
    private javax.swing.JLabel serviceTax;
    private javax.swing.JLabel subTotal;
    private javax.swing.JLabel testing;
    private javax.swing.JLabel testing1;
    private javax.swing.JLabel testing2;
    private javax.swing.JLabel testing3;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
